export const UPDATE_DATE_RANGE = "UPDATE_DATE_RANGE";
export const UPDATE_SELECTED_DATA_SOURCE = "UPDATE_SELECTED_DATA_SOURCE";
export const UPDATE_DATA_CATEGORY = "UPDATE_DATA_CATEGORY";
export const UPDATE_DATA_TYPE = "UPDATE_DATA_TYPE";
