/**
 * COMP90024 Cluster and Cloud Computing Team 12
 *
 * @Author: Haowen Shen
 * Email: haoshen@student.unimelb.edu.au
 */
export const OVERVIEW_DATA_RECEIVED = "OVERVIEW_DATA_RECEIVED";
export const VIC_LGA_OVERVIEW_RECEIVED = "VIC_LGA_OVERVIEW_RECEIVED";
export const RECEIVE_AURIN_DATA = "RECEIVE_AURIN_DATA";
export const RECEIVE_TWEET_COUNT_OF_LGA = "RECEIVE_TWEET_COUNT_OF_LGA";
export const RECEIVE_CORONA_COUNT_OF_LGA = "RECEIVE_CORONA_COUNT_OF_LGA";
export const RECEIVE_SENTIMENT_OF_LGA = "RECEIVE_SENTIMENT_OF_LGA";
export const REVIEW_HASHTAG_OF_LGA = "REVIEW_HASHTAG_OF_LGA";
export const REVIEW_HASHTAG_OVERVIEW_OF_LGA = "REVIEW_HASHTAG_OVERVIEW_OF_LGA";
export const RESET_LGA_DATA = "RESET_LGA_DATA";
export const RECEIVE_USER_SENTIMENT = "RECEIVE_USER_SENTIMENT";
export const UPDATE_SEARCH_BOX_LOADING_STATUS =
  "UPDATE_SEARCH_BOX_LOADING_STATUS";
