export const OVERVIEW_DATA_RECEIVED = "OVERVIEW_DATA_RECEIVED";
export const VIC_LGA_OVERVIEW_RECEIVED = "VIC_LGA_OVERVIEW_RECEIVED";
export const RECEIVE_AURIN_DATA = "RECEIVE_AURIN_DATA";
export const RECEIVE_TWEET_COUNT_OF_LGA = "RECEIVE_TWEET_COUNT_OF_LGA";
export const RECEIVE_CORONA_COUNT_OF_LGA = "RECEIVE_CORONA_COUNT_OF_LGA";
export const RECEIVE_SENTIMENT_OF_LGA = "RECEIVE_SENTIMENT_OF_LGA";
