export const UPDATE_MAP_FULL_SCREEN_STATUS = "UPDATE_MAP_FULL_SCREEN_STATUS";
export const UPDATE_MAP_CENTER_AND_ZOOM = "UPDATE_MAP_CENTER_AND_ZOOM";
export const UPDATE_LAST_CLICKED_INFO = "UPDATE_LAST_CLICKED_INFO";
